### PR TITLE
Total number was again wrong

### PR DESCRIPTION
**Pull request by kate-v-stepanova**
(Sorry)

### CODE REVIEW

**Comment by kate-v-stepanova** [comment]
Sorry, but I messed up with it again. Hope, now it's the last time :(

**Comment by ewels** [comment]
Hah, no problem. Is this deployed on stage and tested? :wink:

**Comment by kate-v-stepanova** [comment]
yep

**Comment by Galithil** [comment]
Now this I like.

**Comment by ewels** [comment]
@kate-v-stepanova - you should frame the above comment ;)

**Comment by kate-v-stepanova** [comment]
@ewels  what's wrong with this comment?

**Comment by ewels** [comment]
@Galithil saying that he likes your code! He doesn't often give out complements :smile:

**Pull request merged**
