### PR TITLE
Workset Placement

### PR DESCRIPTION
**Pull request by Galithil**
This is the first fully functionnal model of the workset placement in genstat. 

It's up on stage.

### CODE REVIEW

**Comment by Galithil** [comment]
@ewels I know what you're going to say already.

@vezzi what do you think ?

**Comment by ewels** [comment]
How do I use it? 😞 
Maybe a line of text explaining what the page would be good, for unfortunate genstat travellers who end up there and feel as confused as I do.

**Comment by ewels** [comment]
Also, #000000 for the border? Come on now, I thought that we agreed that #333333 is the way to go..? ;)

**Comment by Galithil** [comment]
How to use it : enter the url or the id of a lims setup workset step and click next, or change the selects.

**Comment by Galithil** [comment]
https://genomics-status-stage.scilifelab.se/workset_placement

**Comment by Galithil** [comment]
Can I send that to prod so people can try it ?

**Comment by vezzi** [comment]
fine with me... maybe take away the possibility to submit the results to LIMS so we avoid unexpected interactions/behaviours

**Comment by Galithil** [comment]
well, how are they supposed to test wether it works if I remove part of it ?

**Comment by Galithil** [comment]
okay, removed lims update, anything else ?

**Comment by vezzi** [comment]
not on my side... I can merge if no one else wants to check this.. maybe @ewels

**Comment by ewels** [comment]
I haven't really done anything with this, as I never use the LIMS and don't have any IDs to play with (also lack of time / attention). I'd still like there to be a sentence explaining what the purpose of the page is, and the next time I submit a PR I'll probably try to sneak in a nicer border instead of `1px solid black`, but that's about all I can say without seeing anything else..

**Comment by Galithil** [comment]
I changed it to #333333 already

**Pull request merged**
