### PR TITLE
Bioinfo tab: Update status when setting delivery date

### PR DESCRIPTION
**Pull request by kate-v-stepanova**
as usually, deployed on stage: https://genomics-status-stage.scilifelab.se/bioinfo/P6210

### CODE REVIEW

**Comment by ewels** [comment]
Assigning @vezzi and @senthil10 as I don't really know anything about the delivery page interface, so I'm probably not the right person to review this.

@kate-v-stepanova - any chance you could provide a description of what you're changing here? It's quite a large PR..

**Comment by vezzi** [comment]
Hi @kate-v-stepanova I assume that the example become old... can you provide us with a new one we can play with?

**Comment by kate-v-stepanova** [comment]
@vezzi this one for example: https://genomics-status-stage.scilifelab.se/bioinfo/P6412
@ewels actually it's not so big as it looks like. 
1. Thing that you see a lot of changes in html - is only fixing table layout which was a bit wrong (moved <th> tags inside of <thead> instead of <tbody>) which looks big, but it's only 2 lines which have been moved.
2. I don't already remember all the changes exactly. But mainly it's about changing the status of the row (on flowcell, lane or sample level), when delivery date is set or reset.
3. Disable rows which have status 'Delivered'.
4. Optimizing couple of js functions, as I discovered `.nextUntil(some_selector)` function instead of going through all the rows with `.each()` function and checking if they match `some_selector` (works much faster)

**Comment by ewels** [comment]
Sounds good! Thanks!

**Pull request merged**
