### PR TITLE
rewriting the worksets fetching for the project page

### PR DESCRIPTION
**Pull request by Galithil**
This optimizes the data fetching from the workset db

### CODE REVIEW

**Comment by Galithil** [comment]
Now it also adds a button from the samples tab in the project page to the reads_total thingy

**Comment by Galithil** [comment]
I made a new one. I'll PR it once this is merged.

**Comment by kate-v-stepanova** [comment]
It seems to be fine to me. Can I merge?

**Comment by Galithil** [comment]
Sure

**Pull request merged**
