### PR TITLE
Switched quota homepage overview %age for TB Free. 

### PR DESCRIPTION
**Pull request by ewels**
Also stopped Stopped bars being over 100% wide and overflowing the table.

Tested locally and seems to work fine. Can put on stage if anyone wants, but not a big change.

### CODE REVIEW

**Comment by ewels** [comment]
Where are you looking? This is probably from the last PR, need to remove the `_nobackup` projects from the config file.

**Comment by kate-v-stepanova** [comment]
On the localhost, but there shouldn't be a difference? The CPU hours are undefined as well

**Comment by ewels** [comment]
You need this in your localhost `settings.yaml`:

```yaml
uppmax_projects:
  - b2013064
  - a2015205
  - a2012043
```

**Comment by ewels** [comment]
Happy for me to merge?

**Comment by ewels** [comment]
Thank you @Galithil!

**Pull request merged**
