### PR TITLE
Pricing quote and products page

### PR DESCRIPTION
**Pull request by alneberg**
A page where pricing quotes can be created:
 - [x] add products to a quote
 - [x] change the exact number of each products
 - [x] non-integer values allowed, e.g. 1/2 flowcell
 - [x] possible to switch between Swedish academia, industry (or foreign academia) or internal
 - [x] calculates total sum for all three different scenarios
 - [x] checks that the minimum number of products ordered is correct

A page where pricing products are listed.

Live demo at:
https://genomics-status-stage2.scilifelab.se/pricing_quote

### CODE REVIEW

**Comment by ewels** [comment]
Love it! Minor thing - I think we agreed not to call `Re-Run fee` that. Maybe just `Overhead` or something? Probably good to remove all mention of that so that it doesn't creep in again by accident..

**Comment by ewels** [comment]
Also, I think we always round up to the nearest crown, so no need for decimals in the final result.

**Comment by alneberg** [comment]
Thank you @ewels! I exchanged the 're-run fee' with 'overhead' but I'll keep the decimals for now as I don't know if it should be rounded up or just rounded off. It's an easy fix if it's part of the project coordinators feedback.

**Comment by ewels** [comment]
I am pretty sure that it's round up, but yeah - check with @ormestad first 😉

**Comment by alneberg** [comment]
Ok, bug where the dataTable search function was not working is now fixed. Ping @remiolsen! Sorry, I know this is a fairly large PR. The frontend will go through internal beta-testing with the project coordinators so it's more important to review the backend parts.

Thanks!

**Comment by ormestad** [comment]
> I am pretty sure that it's round up, but yeah - check with @ormestad first 😉

Yes it's rounded up!

**Comment by alneberg** [comment]
Ok, changed to rounding up the total sums. Thanks @ormestad!

**Pull request merged**
