### PR TITLE
Quota decrease: show warning if quota will be decreased

### PR DESCRIPTION
**Pull request by kate-v-stepanova**
quotas page: https://genomics-status-stage.scilifelab.se/quotas

on home page it will only display the warning if it's less then 30 days before quota decrease, something like that: 
bildschirmfoto 2016-06-23 um 12 25 49

### CODE REVIEW

**Comment by ewels** [comment]
Awesome! 👍

**Comment by senthil10** [comment]
Maybe this is too late but there was a switch between `NAS`es quite a while ago. Which means `Irene` is now connected to `NAS-8` and `Dorothy` to `NAS-7`. @kate-v-stepanova can you fix this whenever you make next PR or could it be fixed without making a PR (like changing some config file) 👀

**Comment by kate-v-stepanova** [comment]
@senthil10: done! it's just in a config file (`run_dir/settings.yaml`)

**Comment by senthil10** [comment]
😄  😄 

image

**Pull request merged**
