### PR TITLE
Repalce "import *" with "import <some>Handler" in status_app.py

### PR DESCRIPTION
**Pull request by kate-v-stepanova**

### CODE REVIEW

**Comment by ewels** [comment]
Why?

**Comment by kate-v-stepanova** [comment]
Because then I can see what and from where is imported

**Comment by Galithil** [comment]
That's borderline crazy. Is it that hard to grep the handler name from the files in the status folder, or to search from the github repo ?

**Comment by kate-v-stepanova** [comment]
Yes, but why would you do that, if it's not the right way. "import *" is doing a lot of imports that we don't need. Also, when I want to add a new handler, why would I search in all the files if I just can see what we already have and put it in the module where it fits better

**Comment by ewels** [comment]
Whilst I agree that `import *` is bad practice, I'm not sure that the extra imports are having a noticeable impact on speed. I think that the code is quite a bit easier to read with explicit name spaces too (`status.worksets.WorksetSearchHandler` instead of `WorksetsDataHandler`). This is where I tend to go when I'm looking for existing handlers - to the page URLs instead of digging through a tonne of disconnected import statements at the top of the page :confused:

**Comment by pekrau** [comment]
I think 'from xxx import *' is generally frowned upon. It may be ok if the module is built for that purpose, such as a module containing utility functions or a set of constants.

And I think Kate has a point, it makes it easier to see directly from where a function or class comes.

**Comment by kate-v-stepanova** [comment]
`status.worksets.WorksetSearchHandler` that would work as well. But I disagree that we should use `import *` :(
Also, because of that, there were a few imports missing. Like requests or json. By `import *` they were just imported from other modules where they were used too. Which is also not the right way.

**Comment by Galithil** [comment]
Which imports are we doing that are not needed ? All the files imported with * have handlers, and we need all of them, If one of them is not needed, then the code should be removed entirely. 

Also, as @ewels says, there is already a list of handlers when we correlate them to urls. The only thing you get from explicitly importing them is that you can know where they come from without having to do one grep. 

However, it also forces you to remember to update status_app.py in two different places when you want to add a new handler. 
I don't really see the gain, but I can see the loss in maintenance. 

It also will force everyone to use branches for development, as this file must be updated with every new handler you have : if you are working on two different things at the same time, managing them completely separately is going to require juggling skills.

**Comment by pekrau** [comment]
Both @kate-v-stepanova  and @Galithil  have points (I know, Swedes are conflict-averse, and want everyone to be one happy family).

For the case @Galithil mentions, one could use the \_\_all\_\_ construct in the module to be imported, which restricts the stuff that is imported using 'from ... import *' to those features explicitly named.

**Comment by kate-v-stepanova** [comment]
When you want to add a new handler, you would probably need to update status_app.py anyway - in case you handler handles a new url.
Loss of maintanance for whom? If somebody new will look in this code, I don't think it will be easy to understand what's going on there.

**Comment by remiolsen** [comment]
Interesting discussion, and I guess this it is inevitable as gen-stat has ballooned in size over the years. I'm slightly leaning towards the explicit imports even if that means a big ugly block of import statements. People working on `status_app.py` should know what they are doing in any case, but @Galithil has a point that this makes it easier to make mistakes.

**Comment by Galithil** [comment]
Before : Look at the url list, find the handler. copy/paste the handler in github search, find the right file. If you don't like GH, ```grep <handler> status/*``` does the trick.  

Now : Look at the url list, find the handler. Search for the handler in the imports, find the right file.

I'm not sure I see the gain. Try it for yourself : check how long it takes to figure out where ```RunningNotesDataHandler``` comes from.

**Comment by kate-v-stepanova** [comment]
Ok, then what about Phil's suggestions? to use `import status.worksets` and then `status.worksets.WorksetHandler` there you will also see imediately where it is imported from. 

In the url list, I would just do `control + click`, and it jumps to the place where the Handler was defined.

**Comment by Galithil** [comment]
Sure, but since the imports are declared on multiple lines as there is so
many of them, I don't find it actually helpful. I just see more than 20
import lines that are a pain to look into. The line where
RunningNotesDataHandler is declared is
```ProjectSummaryUpdateHandler, ProjectTicketsDataHandler,
RunningNotesDataHandler, UppmaxProjectsDataHandler```
which doesnt help you, you need to look for the declaration, located three
lines above.

 I keep saying the same thing over and over : I don't see the improvement,
but I can see that these 25 lines of import are not going to get smaller
anytime soon, quite the opposite.

On Mon, Nov 30, 2015 at 12:06 PM, kate-v-stepanova <notifications@github.com
> wrote:

> Ok, then what about Phil's suggestions? to use import status.worksets and
> then status.worksets.WorksetHandler there you will also see imediately
> where it is imported from.
>
> In the url list, I would just do control + click, and it jumps to the
> place where the Handler was defined.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SciLifeLab/genomics-status/pull/239#issuecomment-160599270>
> .
>

**Comment by kate-v-stepanova** [comment]
It's nowhere recommended to use `import *`. If the genomics-status is big, it doesn't mean that we should use solutions like that to have a few lines less.

You can also make just one line `import *` if you put all the handlers in one file, but we don't do that -> because it's ridiculous. The same thing with `import *`- is something that we should avoid to use.

**Comment by Galithil** [comment]
I still don't like it, but we'll see how it impacts dev work

**Pull request merged**
