### PR TITLE
changes for xten flowcells

### PR DESCRIPTION
**Pull request by Galithil**
Since I am the one parsing the Xten flowcells, I can also store more info in statusdb, and thus, display more info in the flowcell page.
Will that ever work also for Hiseq and Miseq ? Maybe. This gets data from the views anyway, so as long as the view contains the right keys, it should be doable... but that would mean rewriting the parser for Hiseq & Miseq runs ...

### CODE REVIEW

**Comment by Galithil** [comment]
before someone asks : it is not deployed on stage because the xten data does not exist on stage.

**Comment by guillermo-carrasco** [comment]
who was gonna ask that? :-P

**Comment by ewels** [comment]
Who, me? :wink: 

This is irrelevant but made me laugh, and I haven't posted a meme for a while:
come at me

**Comment by Galithil** [comment]
Okay I'll deploy it on stage and you stop posting pictures of crazy old ladies. 
Here : https://genomics-status-stage.scilifelab.se/flowcells/150424_BH2WY7CCXX#

**Comment by ewels** [comment]
Nice! I just noticed that you have the `.no-margin` class on the new table, which is probably why it has no margin and we had to add a nonbreaking space :grinning:

Any chance you could `text-align: right` on the `<th>` elements on the new table? I think it might be a little clearer to read then, currently each label is closest to the incorrect field. Minor thing though.

**Comment by ewels** [comment]
oh, I almost forgot:

# The Queen Approves
queen approves
(of deployment on stage)

**Comment by Galithil** [comment]
@ewels read  look at the last commit, look at stage and tell me if you think it's better ... :p

**Comment by ewels** [comment]
Yeah, does look a bit odd. Fine by me to put it back if you'd rather :)

**Comment by Galithil** [comment]
This was not merged on time, so now it's a bit late to do that. head over https://github.com/SciLifeLab/genomics-status/pull/207.

**Pull request closed without merging**
