### PR TITLE
Hopefully the final Bootstrap update

### PR DESCRIPTION
**Pull request by aanil**

### CODE REVIEW

**Review by sofiahaglund — COMMENTED** [review]
Woah! 43 files! :-O

One question- is this on stage yet? :-)

**Comment by aanil** [comment]
Up on stage now!

**Review by sofiahaglund — APPROVED** [review]
Great job!

  I think some pages, or at least part of them or some functionalities seem dead, but I don’t think that’s related to your bootstrap update code. 
  The NAS quotas page isn’t showing any data for me, but maybe the data isn’t connected to stage?  Same thing with the instrument logs.   
  The project meta comparison tool is also not working, but it seems dead currently on prod as well 😄 
  
    I just have one issue- do we want it to be this easy to delete a user in the user management page? 😆  I can’t delete myself bu-huu! 😭

**Review by alneberg — APPROVED** [review]
Awesome! Now Bootstrap 5 is the new normal! Just waiting for the stable release to do all this again...

**Pull request merged**
