### PR TITLE
change the project/workset/flowcell lists

### PR DESCRIPTION
**Pull request by Galithil**
Worksets and flowcells table will be written via the tornado templating system
the projects is too big to go under such a change, so the new javascript library has just been added on top.

Can be seen on stage.

### CODE REVIEW

**Comment by ewels** [comment]
Nice, looks good to me! Haven't read the code though ;)

**Comment by guillermo-carrasco** [comment]
hej! looks good both in stage and the code, didn't see anything weird. I was just thinking, does this "deprecate" any API call? `/api/v1/flowcells` maybe? If so maybe you want to just remove it.

**Comment by Galithil** [comment]
I'd rather keep them in case we need to reload the table ​client side. that
might be useful, since DataTAbles can take a json input.

**Comment by guillermo-carrasco** [comment]
You can always use git history for that and keep the production code clean, don't you think?

**Comment by Galithil** [comment]
I don't really like the idea of removing an API call that works perfectly
and could be used by others applications or local scripts to get the
flowcell data without having to get the whole HTML page. I tend to use the
api calls to get the data directly without bothering with the HTML when I'm
looking for specific info that would be a pain to find in futon, or for
debugging purposes.
It does not slow anything, and gives one more access point for the data.

**Comment by guillermo-carrasco** [comment]
fair enough then, cool!

**Pull request merged**
