### PR TITLE
Bug fix: code injections in the running notes

### PR DESCRIPTION
**Pull request by kate-v-stepanova**
that was a funny thing. 

In the running notes I could enter something like
```<button id='test' type='button'>Hack test</button>
<script>
$('#test').on('click', function(e) {
console.log('hack works!');
// you can call here api
// or send thousand emails to everyone@scilifelab.se
// or anything bad whatever you can do with javascript
});
</script>```

and we had a button that was executing whatever stuff you write in the `<script>` block

### CODE REVIEW

**Comment by Galithil** [comment]
isnt this going to interact with the markdown module ?
Security wise, since Genstat is closed-access, it's not an issue yet, but given the recent talks, that could change...

**Comment by kate-v-stepanova** [comment]
markdown doesn't use this kind of symbols `<`, so shouldn't be a problem

**Comment by ewels** [comment]
Could you deploy this on stage please @kate-v-stepanova so we can give it a check over before deploying?

**Comment by kate-v-stepanova** [comment]
yep, deployed

**Comment by ewels** [comment]
Hmm, seems to be the same behaviour when I try this:
https://genomics-status-stage.scilifelab.se/project/P193

```
Can i <input type="text" value="hack it">? Yes I can!
```

image

**Comment by ewels** [comment]
What happened to the jQuery object creation idea?

**Comment by kate-v-stepanova** [comment]
why does it work for you, but doesn't work for me? I can see only this ```Can i <input type="text" value="hack it">? No, I can't!```

**Comment by ewels** [comment]
Hmm, works for me now. Must have been a caching error on my side sorry..

**Comment by ewels** [comment]
This approach breaks block quotes:

```markdown
Some text
> Here is a
> quote that I'm quoting
```

Before: 
image

After: 
image

But frankly, I'm pretty sure that I'm the only person who would notice that..

**Comment by Galithil** [comment]
I'm really not sure to see the point, since anyone can use javascript in their browser anyway... If you could use that to open a shell or execute python server side, I could see the issue, but javascript is always run on the user's side anyway... 

I guess that if you really wanted to be a pain, you could insert a running note with malicious js that would download a file to anyone who sees the running note.. but there would still be your name on the running note, so that probably wouldnt go _that_ well.

**Comment by kate-v-stepanova** [comment]
Seriously?? Not fixing this thing, just because 'Nobody will use it anyway' I don't think I agree with this approach. Maybe nobody would use it in purpose, but maybe they would, who knows? And whatever - it's vulnerability, why would we keep it if it can be fixed just with a few extra lines of code?

**Comment by kate-v-stepanova** [comment]
@ewels you were right `.html()` thing is better :) now quotes are also working

**Comment by ewels** [comment]
Nice! I have just thought of one small thing though - when I first wrote this I remember that @jgruselius  was excited about being able to write custom HTML. I think that this was mostly so that he could write custom links though, which can be done in markdown. But any old running notes will now look bad.

**Pull request merged**
