### PR TITLE
Flowcells page updates

### PR DESCRIPTION
**Pull request by ewels**
- Added percentage of undemultiplexed reads for each type
- Highlighted unrecognised barcodes if they match a known barcode, but with Ns
- Did some clever number formatting which allows numbers to be copied to the clipboard raw
- Truncated a few numbers to 2 decimal places and added some % signs
- Moved the button to the left and made it blue (after I asked @Galithil to make it not blue, sorry)
- Changed it back to a table again after I told @Galithil not to make it a table, to accommodate third column and facilitate copying to excel

Running on stage: https://genomics-status-stage.scilifelab.se/flowcells/150626_BH3JMMCCXX

### CODE REVIEW

**Comment by ewels** [comment]
A few re-written chunks, thanks to @Galithil for feedback.

**Comment by Galithil** [comment]
yup, should be fine. We could go for recursion in nice_numbers, but I can sense that you're not fond of it, so ...

**Comment by ewels** [comment]
Did you merge already? That was fast.

**Comment by Galithil** [comment]
well, we went through every change and rewrote half of them, so yeah, I
think that is good enough :D

**Comment by ewels** [comment]
yeah - i don't mean because it might not be ready for deploying, more that i went to do it myself as soon as i saw the merge and it was already up to date :)

**Pull request merged**
