### PR TITLE
FC plot to use shared tooltip

### PR DESCRIPTION
**Pull request by remiolsen**
I strongly disagree that the same should be done for the FC trend plot. It works for a stacked bar chart but not for the trend plot.

### CODE REVIEW

**Comment by ewels** [comment]
Ok cool 👍  Is this on stage?

**Comment by remiolsen** [comment]
Yup!

**Comment by ewels** [comment]
Usability suggestions:

* Use a fixed location for the tooltip to stop it jumping around so much
    * eg. https://api.highcharts.com/highcharts/tooltip.positioner (and [example](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/positioner/))
* Use a table in the tooltip and right align the numbers in their own column

In what way does it not work for the FC trend plot?

**Comment by remiolsen** [comment]
>In what way does it not work for the FC trend plot?

In the sense that it is too crowded. But also that the points don't share an X-axis, i.e they can be seen as a barchart only with invisible bars, if that makes sense.
A shared tooltip will make it jump all around, yes that can be remedied with a fixed location. It will also make selecting points more imprecise, for instance fo what I think is the most common use case is to click on anomalies. 

I agree for the count plot. It would make the tooltip less jumpy.

**Comment by remiolsen** [comment]
Ping @ewels 

`followPointer` seems to work nicely.

**Comment by ewels** [comment]
Awesome, makes all the difference 😉  👍

**Pull request merged**
