### PR TITLE
Replace Internal costs with new Sticky running note

### PR DESCRIPTION
**Pull request by aanil**

### CODE REVIEW

**Review by sofiahag — APPROVED** [review]
Looks good!

My only comments are that I think it would look better if we remove the `margin-left: 0.5em` from .`mx-2` for the latest sticky running note, and also maybe add some padding/border to the top of the note so it's more centered :-P 

I like these colors :-D 

sticky: #9468fc
invoicing: #d063ff

Or something similar?

Skärmavbild 2023-02-20 kl  16 06 03

**Review by alneberg — APPROVED** [review]
Looks good! Nice to get rid of some more code. I agree with Sofias suggestions, but I think we can skip fixing the margin if it's too much work. The new colours Sofia suggests are indeed better, but I could live with the ones in the PR as well.

**Comment by aanil** [comment]
Changes up on stage!

**Comment by sofiahag** [comment]
Looks good!

**Pull request merged**
