### PR TITLE
color according to q30

### PR DESCRIPTION
**Pull request by Galithil**
makes the plot display the q30 colors, but slightly darker because else you can't see anything.

Looks like this : 
chart 2

### CODE REVIEW

**Comment by ewels** [comment]
Nice! How about these colours?
```
#3c763d (green)
#8a6d3b (yellow)
#a94442 (red)
```
or if those are too dark, these:
```
#d0e9c6 (green)
#faf2cc (yellow)
#ebcccc (red)
```

**Comment by Galithil** [comment]
I kept the same hue as the bootstrap classes but darkened them. I can use yours if you prefer, I don't really mind

**Comment by ewels** [comment]
Yeah, I wondered if you'd done something like that. Mine are bootstrap colours from the text used in alert boxes. Bootstrap has a range of different colours for `success` / `danger` etc which vary by more than just lightness depending on their use.

**Comment by Galithil** [comment]
we finally agreed.

**Comment by ewels** [comment]
Deploy!

**Pull request merged**
