### PR TITLE
Fix indentation and change colors/novaseq lines cver

### PR DESCRIPTION
**Pull request by sofiahag**
I noticed the colors had messed up with the addition of the NovaSeqXPlus. The threshold line colors of the NovaSeq were also wrong.
I think this looks better?

I've just installed a VS Code extension, which checks consistent indentation, so it was an easy fix 😛 

Up on stage!

### CODE REVIEW

**Comment by alneberg** [comment]
Great! I think it looks better as well. Do you think we have a threshold line for 10B we can add already?

**Comment by sofiahag** [comment]
> Great! I think it looks better as well. Do you think we have a threshold line for 10B we can add already?

Yes, it looks like we do from the AM doc draft, 1000 M? I added it, up on stage!

**Comment by parlundin** [comment]
> > Great! I think it looks better as well. Do you think we have a threshold line for 10B we can add already?
> 
> Yes, it looks like we do from the AM doc draft, 1000 M? I added it, up on stage!

Bit confused here, the line is the threshold for the whole FC? 1000M is per lane. 10B should then be  10000 if we follow Illumina specs. But we say 1000M/lane so internally 8000M for a FC?

**Comment by sofiahag** [comment]
> > > Great! I think it looks better as well. Do you think we have a threshold line for 10B we can add already?
> > 
> > 
> > Yes, it looks like we do from the AM doc draft, 1000 M? I added it, up on stage!
> 
> Bit confused here, the line is the threshold for the whole FC? 1000M is per lane. 10B should then be 10000 if we follow Illumina specs. But we say 1000M/lane so internally 8000M for a FC?

Right, ok, I was following the logic of the other lines. So, do you think we should change the other threshold values of the graph, then? I don't remember how we came up with the values of the lines 🤔 😆

**Comment by sofiahag** [comment]
Updated to value based on 8 lanes, up on stage!

**Comment by alneberg** [comment]
Now we have this issue instead.... 
Screenshot 2023-11-09 at 12 14 51

Not sure how to solve it though

**Comment by sofiahag** [comment]
> Now we have this issue instead.... Screenshot 2023-11-09 at 12 14 51
> 
> Not sure how to solve it though

I left-aligned the NovaSeqXPlus label, it's up on stage, what do you think? We could also just have one line, and have labels in one?

**Comment by alneberg** [comment]
Ah, nice! I like it! But just to be even more picky, can we switch places of Xplus and S4? Last one, promise!

**Comment by alneberg** [comment]
It's just so that the 10B is where it will always be, and then we can just delete the s4 when they are not used anymore. But yes, one could argue for the opposite as well.

**Pull request merged**
