### PR TITLE
Pimping the new project read counts page.

### PR DESCRIPTION
**Pull request by ewels**
Front end partial re-write of Denis' new project read counts. Main things:

* New summary chart at the top
 * Shows deselected counts as a light grey
 * Clicking a bar takes you to that sample and highlights it
* Fixed some broken html
* Added some titles explaining what stuff is
* A little prettifying, but not much really

### CODE REVIEW

**Comment by ewels** [comment]
Running on stage: https://genomics-status-stage.scilifelab.se/reads_total/P1775

**Comment by ewels** [comment]
merge me

**Comment by vezzi** [comment]
@ewels @Galithil this looks great.
@kate-v-stepanova @sylvinite this part should go in the bioinfo tab or be connected to it. This page is useful to display things. In the bioinfo tab there can be a use or not-use botton that will tell if we have to use or not the sample-run. The information presented in this page is sample-run and I assume denis is getting it directly from the flowcell_x db.

**Comment by ewels** [comment]
Don't close yet - adding some extra description after discussion with @Galithil about how the page actually works.

**Comment by ewels** [comment]
* Don't allow empty search terms
* Better help text (top of page and error message)
* Don't refer to query as "project". Explain how search terms work.

Happy for this to be merged now.

**Comment by ewels** [comment]
Updated stage: https://genomics-status-stage.scilifelab.se/reads_total/P1775

**Comment by ewels** [comment]
More stuff:

* Posh layout to have the summary table at the side of the page
* New button that downloads the contents of the summary table as a file

Updated on stage: https://genomics-status-stage.scilifelab.se/reads_total/P1775

**Comment by ewels** [comment]
Thanks!

**Comment by Galithil** [comment]
You're lucky that Pär liked it :P

**Pull request merged**
