### PR TITLE
Decreasing the font-weight of the badges on the project- and bioinfo info page 

### PR DESCRIPTION
**Pull request by sofiahaglund**
So a couple of us think it is hard to differentiate between the numbers of the badges on the project info page. Therefore I took it upon myself to decrease the font-weight a bit. Instead of editing the bootstrap file I added a custom css. 
I guess it's a bit risky without checking with Phil first, but here goes 😜

### CODE REVIEW

**Comment by remiolsen** [comment]
To ask the inevitable question: is this change on genomics-status-stage?

It sounds like a good change, but I have no idea of how it looks or what the css does 😉

**Comment by remiolsen** [comment]
I like it! It's much easier on the eyes :+1:

Couldn't you just add these lines to `status.css` in stead of making a new `.css` file?

**Comment by sofiahaglund** [comment]
Maybe I can- I'll look into it 🤔

**Comment by sofiahaglund** [comment]
Hmm, can't really get it to work for me, but I can keep looking. I agree that it's unnecessary to add a script with only 3 lines of code 😊 unless we will make additional changes to the custom file 😜

**Comment by ewels** [comment]
Cool! Yes, as @remiolsen says - just pop this into `status.css`. If you do this and it has no effect, try forcing a refresh in your web browser (cmd+shift+R) - it's probably caching the old version of the stylesheet.

**Comment by sofiahaglund** [comment]
You're right, of course, now it works 😊

**Comment by ewels** [comment]
Awesome!

Ok, I have a "stretch goal" for you now. You have 12 git commits in this pull request for 3 lines of code 😆 - in these scenarios it's good practice to tidy up your git history a bit. You do this using `git rebase`. Specifically:

```
git rebase -i HEAD~12
```

This will take you into "interactive" rebasing mode (the `-i` flag) for the last 12 commits. Then you can change them all from `pick` to `squash` except for the first one, which you can change to `reword` and change the commit message. If all goes well, those 12 commits will be replaced with 1 with a nice commit message.

The final step is to push to GitHub, but it will complain as the history is now different. This is expected, so you can "force push" to overwrite the GitHub copy with your copy:

```
git push --force
```

**Comment by ewels** [comment]
Awesome work! I'm not sure I've seen combined author commits like that before, nice! 😁

**Comment by ewels** [comment]
haaaang on a minute, something's not right:

image

**Comment by sofiahaglund** [comment]
I'll re-do the pull request

**Comment by ewels** [comment]
See #393

**Pull request closed without merging**
