### PR TITLE
Change FC yield plot to lines

### PR DESCRIPTION
**Pull request by remiolsen**

### CODE REVIEW

**Comment by ewels** [comment]
Great! Is this up on stage? Could you paste a couple of quick links for testing?

**Comment by remiolsen** [comment]
@ewels Sorry, I actually don't have access to stage but I'm trying to get that sorted out.

**Comment by ewels** [comment]
So I guess we're looking at this page? https://genomics-status-stage.scilifelab.se/flowcells_plot

It's super variable! How does it look with just scatter plot points instead of a line?

**Comment by remiolsen** [comment]
@ewels I added an optional scatterplot.

**Comment by ewels** [comment]
Awesome! Do you have access to tools-dev yet? ;)

**Pull request merged**
