### PR TITLE
added xten flowcells

### PR DESCRIPTION
**Pull request by Galithil**
as usual, deployed on stage. There is one pseudo xten flowcell in there for now : https://genomics-status-stage.scilifelab.se/flowcells/150424_BH2WY7CCXX

### CODE REVIEW

**Comment by vezzi** [comment]
@Galithil looks ok to me, I will let someone else give another look at the code.
One general comment:  I am surprised by the "% of the lane" column, as almost always looks like that half of the lane is made by undetermined indexes, but this is not reflected by Yield of number of clusters.. I noticed this in all the flowcells I looked so far... have you any idea of what this number represents? Maybe we should not showed it...

**Comment by guillermo-carrasco** [comment]
The Python code looks ok, maybe @ewels wants to review the JS?

**Comment by Galithil** [comment]
@vezzi  that's why I showed it actually. I don't know what that is, the numbers look weird so I wanted you guys to have a look at it and tel me what to do with it.

**Comment by vezzi** [comment]
Ok, I will contact Illumina about this

FV

**Comment by ewels** [comment]
@guillermo-carrasco: There is no JS in this pull request..? :wink: 

HTML looks good though! You're getting to be a pro at this @Galithil!

bootstrap

**Comment by Galithil** [comment]
Except I did not change anything visually relevant, just piggybacked on what you did ...

**Comment by guillermo-carrasco** [comment]
@ewels I think that `run_dir/static/js/flowcell_samples.js` is JS... am I that bad ad web developing?

**Comment by Galithil** [comment]
No, no, you are perfectly right, that is js. It's mostly conditional cells for the tables though, not very interesting.

**Comment by ewels** [comment]
coffee time

**Comment by guillermo-carrasco** [comment]
hahaha

**Pull request merged**
