### PR TITLE
Adding rec ctrl view

### PR DESCRIPTION
**Pull request by Galithil**
Okay, so this adds a way to visualize quickly what the plates we were sent look like. Someone thought it might become handy.
It looks like this : 
https://genomics-status-stage.scilifelab.se/rec_ctrl_view/P2061#

>Will this work with every project ?

Not really, they need to be updated by the latest version of PSUL first, and on stage, that's hit and miss. Feel free to ask me to update your favorite project to see it there.

>It looks kind of... sad. Can't you add colors ?

I'll give you the crayons if you like, feel free to have a blast.

### CODE REVIEW

**Comment by ewels** [comment]
Stuff said on slack:
* 9 columns, should be 12
* RIN values wrong
* Show `Initial QC Concentration` instead of `user conc.`
* Add number of reads

Otherwise - super awesome!

crayons

**Comment by Galithil** [comment]
I'm going to close this as it's going to go through a serious rewrite. To make more js. sad, heh ?

**Comment by ewels** [comment]
js

**Comment by Galithil** [comment]
https://zombiecodekill.files.wordpress.com/2014/07/javascript-the-good-parts-the-definitive-guide.jpg

**Comment by ewels** [comment]
jquery

**Pull request closed without merging**
