### PR TITLE
Two years in the making

### PR DESCRIPTION
**Pull request by ewels**
* Fixed bug in homepage server status plots
* Updated bootstrap
* Added copy button for project samples table
* Made buttons above project samples table smaller

### CODE REVIEW

**Comment by ewels** [comment]
finally done

**Comment by Galithil** [comment]
Interacting with the user clipboard ? You monster. 
Also, we can now use all the functions the cool bootstrap kids use now ? 

Can I get a stage deploy ?

**Comment by ewels** [comment]
What functions do the cool bootstrap kids use? The main reason I updated bootstrap was because the version we were running didn't have the 'copy to clipboard' icon I wanted to use.

Now running on stage.

**Comment by Galithil** [comment]
eeeeh it works. friggin js.

**Pull request merged**
