### PR TITLE
Add more fields to sequencing queues page

### PR DESCRIPTION
**Pull request by aanil**

### CODE REVIEW

**Review by sofiahaglund — CHANGES_REQUESTED** [review]
Looks good!

But the labels don't show the numbers in Excel again, as for qPCR. Could we add the alerts here as well? 😏

**Review by sofiahaglund — APPROVED** [review]
It's not on stage yet, right? But it looks good!

**Comment by aanil** [comment]
> It's not on stage yet, right? But it looks good!
No, its up on stage!

**Comment by sofiahaglund** [comment]
> > It's not on stage yet, right? But it looks good!
> > No, its up on stage!

That looks better! 👍

**Pull request merged**
