### PR TITLE
Added running notes category 'Important'

### PR DESCRIPTION
**Pull request by sofiahaglund**
It was suggested to add a running notes category called "important", seemed easy enough? :-)

### CODE REVIEW

**Comment by aanil** [comment]
It would be nice to have the option to filter the 'Important' with the others. This is next to the 'Search' input.

**Comment by sofiahaglund** [comment]
> It would be nice to have the option to filter the 'Important' with the others. This is next to the 'Search' input.

It's already there though, right? :-O

**Comment by aanil** [comment]
It shows up now!

**Comment by sofiahaglund** [comment]
> It shows up now!

But are the running notes loading, or do they never load on stage? :-O

**Pull request merged**
