### PR TITLE
Remove quotas & add NovaSeq to plots

### PR DESCRIPTION
**Pull request by remiolsen**
* Removes UPPMAX quotas from homepage
* Removes UPPMAX quotas page
* Adds NovaSeq stats to flowcell trends and flowcell counts plots

Note! Don't deploy before changes to a certain DB view in production has been made.

### CODE REVIEW

**Comment by remiolsen** [comment]
📢📢 **These changes are on genomics-status stage** 📢📢  

@senthil10 @ewels If any of you guys would like to have a quick look

**Comment by ewels** [comment]
Ping me again on Friday :)

**Comment by remiolsen** [comment]
Thanks @senthil10. I've fixed the grid layout for these selectors

**Comment by senthil10** [comment]
Nice @remiolsen , I am done with my review 👍 Since @ewels is back, may be he too can have quick look 😉

**Comment by senthil10** [comment]
Or I will just merge it 😉

**Pull request merged**
