### PR TITLE
Add emails from order portal to project page

### PR DESCRIPTION
**Pull request by remiolsen**

### CODE REVIEW

**Comment by ewels** [comment]
Is it on stage?

**Comment by remiolsen** [comment]
It is now, @ewels. Check out project P9955

**Comment by senthil10** [comment]
Awesome @remiolsen , nicely done :) But the alignment is bit bothering me though, can we do like

```
email1 Contact Lab
email2 Lab
```

or something better ?

**Comment by remiolsen** [comment]
@senthil10 I was thinking the same thing. I'm looking if there's any bootstrap CSS that can make this nice, `<dl class="dl-horizontal">` for instance.

**Comment by ewels** [comment]
Yes - a `<dl>` or even a list would work. I imagine that the current solution could get really confusing with long emails / narrow screens too if they wrap onto multiple lines.. 

Alternatively, could just put the email addresses themselves in a `label` and skip the text saying what it is. They could be colour coded by category and add a tooltip `title` to describe the category when hovering with the mouse.

**Comment by remiolsen** [comment]
Okay, I got a little CSS-happy, but I found something I like. It's on tools-dev, @ewels.

**Comment by ewels** [comment]
Awesome work 👏 

pretty

**Pull request merged**
