### PR TITLE
days in production for closed projects

### PR DESCRIPTION
**Pull request by remiolsen**
I'm somewhat sure I (or someone else), a long time ago, protested against `days in production` having different meanings for open and closed projects.

I think I'm okay with this now.

### CODE REVIEW

**Comment by ewels** [comment]
Protestation overruled 😆 

Looks great, thanks!

**Comment by ewels** [comment]
@remiolsen - would be great if you could deploy 👍

**Comment by remiolsen** [comment]
@ewels It's live now

**Comment by ewels** [comment]
live

**Pull request merged**
