### PR TITLE
Add actual run setup to flowcell page

### PR DESCRIPTION
**Pull request by aanil**
Data added here https://github.com/SciLifeLab/StatusDB_views/pull/109.

Up on Stage!

### CODE REVIEW

**Comment by chuan-wang** [comment]
Hi @aanil , I guess the flowcells page (`run_dir/design/flowcells.html`) also needs to be updated?

**Comment by aanil** [comment]
@chuan-wang The data in flowcells page comes from another view on StatusDB though. Do you want me to include it in this other view too?

**Comment by chuan-wang** [comment]
> @chuan-wang The data in flowcells page comes from another view on StatusDB though. Do you want me to include it in this other view too?

@aanil Yes, I think it would be nice to have it in both `flowcell` and `flowcells`. Thanks!

**Comment by aanil** [comment]
@chuan-wang Added it to flowcells page too!

**Review by chuan-wang — APPROVED** [review]

**Review by alneberg — APPROVED** [review]
Nice addition!

**Pull request merged**
