### PR TITLE
Remove positive and negative controls from Library Validation in qPCR queue

### PR DESCRIPTION
**Pull request by aanil**
As instructed by the lab

### CODE REVIEW

**Comment by sofiahag** [comment]
Is this on stage?

**Comment by sofiahag** [comment]
> > Is this on stage?
> 
> Yep

Thank you! I'll look at it 👍🏻

**Comment by sofiahag** [comment]
Ok, so they don't want the projects to show up at all?

**Comment by aanil** [comment]
They don't want the control projects to show up in Library Validation, only if they are queued for sequencing.

**Comment by sofiahag** [comment]
> They don't want the control projects to show up in Library Validation, only if they are queued for sequencing.

Ok, so not at all, ok, looks good! 👍🏻

**Review by sofiahag — APPROVED** [review]

**Pull request merged**
