### PR TITLE
Plot to see flowcell trends

### PR DESCRIPTION
**Pull request by Galithil**
https://genomics-status-stage.scilifelab.se/flowcells_plot

Open to comments.

related to https://trello.com/c/V4rOWRPQ/497-make-new-plot-in-genstat-to-show-yield-per-flow-cell.

### CODE REVIEW

**Comment by vezzi** [comment]
SO looks great. two request only:
 - add a colour by month filter
 - make default display one year of runs

**Comment by vezzi** [comment]
and when ticking out an instrument would be great if you can make the name also grey, not only the label colour

**Comment by senthil10** [comment]
Awesome :clap: :clap: 

P.S: Noticed the *legend* is unchanged even after changing the "Color by"

**Comment by Galithil** [comment]
@senthil10 because it's not a legend, you can actually click on these to filter by instrument.

**Comment by senthil10** [comment]
Woooo!! That is even more awesome :joy:

**Comment by ewels** [comment]
Looks awesome! Few suggestions, some previously mentioned in person:

- [ ] Plots are maybe a little tall
- [ ] The [default header tooltip](http://api.highcharts.com/highcharts#tooltip.headerFormat) is rubbish, would be nicer if you set it to `<code>{point.key}</code>` or something
- [ ] Add `{this.series}` to the tooltip somewhere, so we can see what machine it is.
- [ ] Maybe consider using a scatter plot instead when there are lots of data points (scales better)
- [ ] You're currently using a sequential colour scale for categories. A categorical scale such as `Dark2` may work better. Or `Paired` as it has more colour options so shouldn't need to use colour interpolation.
- [ ] It would be good if the date selection boxes were prefilled with the currently shown defaults on page load
- [ ] Personally I would have put the toolbar above the plot instead of underneath it. Not sure if this would be an improvement or not though.
- [ ] Consider rotating it 90 degrees and making it a bar plot instead. The axes labels will be much easier to read and you can make the plot taller to fit more bars in.
- [ ] Maybe get the form to submit when changing date instead of relying on the `Search` button. I saw Remi expect it to update a few times over his shoulder and agree it would make it easier.
- [ ] Maybe modify a few of the datepicker defaults:
  - `autoclose: true`
  - `todayBtn: true`
  - `todayHighlight: true`
  - `weekStart: 1`
  - `daysOfWeekHighlighted: "0,6"` (because we're not American :us: )
- [ ] Instead of `Display type` and `Display` as two combination categories, consider putting them into a single dropdown with two sections separated with an [optgroup](http://www.w3schools.com/tags/tag_optgroup.asp)

Also, I hate to say this after you built something so attractive, but why have the clickable names below the graph instead of using a HighCharts legend? Clicking the legend series already shows / hides those datasets so it's the same functionality as far as I can see. Try clicking the legend in [this demo](http://www.highcharts.com/demo/line-basic)

Ok, brain dump over. Sorry it's so long - I got a bit over excited! :grin:

**Comment by ewels** [comment]
- [ ] Reducing the [`groupPadding`](http://api.highcharts.com/highcharts#plotOptions.column.groupPadding) will make the bars closer together which will look better I think.

**Comment by Galithil** [comment]
1- yes
2- maybe
3- no
4- maybe
5-  can't find doc about it
6- yes
7- not sure it matters
8- it seems to be fine currently with ~1600 bars
9- it will get messy when you want to change both dates, you'll have to wait for a full reload. 
10- yes
11- I'd rather not. They are completely separated in the code, and I want to accentuate that aspect.
12- The legend only works if the points have all the information you want to filter on. Most often, they don't. Is there a way to store multiple fields of information in the points ?
13- since the default view went to 1 year, I don't think we need that anymore.

**Comment by Galithil** [comment]
Also, I deployed the new version on stage.

**Comment by ewels** [comment]
I updated my comment so that it was numbered. But your comments now don't match and I'm confused.

1. Great
2. Is easy! Just need a new base level `tooltip` config key. eg. [here](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/tooltip/footerformat/)
3. Agreed, if you're not using series then no need to report series name.
4. Still think that this is worth playing with.
5. Main ColourBrewer docs are [here](http://colorbrewer2.org/), describing `sequential`, `diverging` and `categorical` scales. Names of `color.js` scales are [here](https://camo.githubusercontent.com/7156603076d2d5fdf5639649843b5c018c6b7c2f/68747470733a2f2f7261772e6769746875622e636f6d2f676b612f6368726f6d612e6a732f633137613966636433613662353864396535353436643339333664303739353165396235386333302f64656d6f2f616c6c636f6c6f72732e706e67)
6. 👍 
7. EVERY DETAIL MATTERS! Ok fine, you're right, it doesn't really matter.
8. Fair enough. Prepare for me to say _"I told you so"_ in a year. Some role reversal here?
9. Yeah, I guess. Hmm. What would be awesome would be a proper range selection like on [Kayak.co.uk](https://www.kayak.co.uk/) and other sites. Not aware of a plugin that will do it properly though.
10. 👍 
11. Fair enough. This suggestion was mostly because it's currently possible to get invalid combinations by switching back and forth (eg. Q30 at flowcell level was it?). Having a single dropdown is an easy way to avoid that.
12. The legend only works if the data is separated into multiple series. Sounds like you're not doing this, so probably not an easy way to get it to work.
13. Still think it'd look better with less spacing between bars ;)

**Comment by Galithil** [comment]
I rewrote the tooltip and lowered the droupPadding. I don't see much of a difference, but that's probably because I'm not a true designer. 
About colors : I'm not fond of using a billion different modules just to get colors, and I like my new scheme.

Merge ?

**Pull request merged**
