### PR TITLE
Flowcell page moved to python

### PR DESCRIPTION
**Pull request by kate-v-stepanova**

### CODE REVIEW

**Comment by kate-v-stepanova** [comment]
deployed on stage: https://genomics-status-stage.scilifelab.se/flowcells/160822_D00450_0264_AHYWC2BCXX

**Comment by Galithil** [comment]
It seems that there is a view missing.

**Comment by Galithil** [comment]
Could you make sure that the headers have non breaking spaces instead of normal spaces ? it messes up the layout a bit.

**Comment by kate-v-stepanova** [comment]
The view is fixed. It wasn't deployed on production, so when stage updated today, the views were removed. 
About headers, not sure, what exactly do you mean?

**Pull request merged**
