### PR TITLE
Show instrument name for the server status

### PR DESCRIPTION
**Pull request by kate-v-stepanova**

### CODE REVIEW

**Comment by kate-v-stepanova** [comment]
@ewels we need your opinion! @vezzi is suggesting to place the table under the `Storage usage` table, but I remember you didn't like this idea
What do you think? 
https://genomics-status-stage.scilifelab.se/#

**Comment by ewels** [comment]
It is getting a bit wide with the names now. Yeah, under `Storage Usage` could work I guess. That or more `Latest Updated Data` under `Storage Usage` instead as that's probably less important. Either is good.

**Comment by kate-v-stepanova** [comment]
I personally like this one more - I think it's more logical when both tables with disk usage are on the left, and latest data on the right. I commited this one
bildschirmfoto 2016-02-25 um 13 34 25

And this is alternative, if you like it more - I can put this one, just let me know which one you like more, @ewels @vezzi 
bildschirmfoto 2016-02-25 um 13 34 09

**Comment by ewels** [comment]
Hah, your screen is massive :) This is how your screenshot shows for me:
image

But yeah, I agree - top one is nicer.

**Comment by kate-v-stepanova** [comment]
Ok, then feel free to merge! ;)

**Pull request merged**
