### PR TITLE
Updated DataTables to version 1.13.6

### PR DESCRIPTION
**Pull request by sofiahag**
I noticed that the worksets page doesn't have the same sorting class as the other tables, is there a reason for this? 

Maybe there is, but I made a separate commit adding the same class just in case it's an oversight.

### CODE REVIEW

**Comment by sofiahag** [comment]
Up on stage!

**Review by aanil — COMMENTED** [review]
I thought we agreed we were gonna download the file instead of using the CDN link? 

It would also be better to switch it one table at a time.

**Comment by aanil** [comment]
We will also keep `jquery.dataTables.min.js` for now.

**Comment by sofiahag** [comment]
> I thought we agreed we were gonna download the file instead of using the CDN link?
> 
> It would also be better to switch it one table at a time.

Hm ok, I thought we said yesterday that we were not going to download the file 😆 ok, no worries! I'll fix it.

Yes, I just thought, since it's such a small change we could add it all at once, but ok, I can do just one file, do you have a preferred one? 😏

**Comment by alneberg** [comment]
Yes I agree with Anand, I meant that we should keep the file datatables downloaded. It looks really promising though that it seems to be such a small change! I guess we could change all as well, but we need to test them all individually and then also let people know that this change has happened so that we can collect the neccessary error reports

**Comment by sofiahag** [comment]
OK, I've tested it quite a bit but maybe you guys have different procedures on how to test it even more thoroughly :-) 

I'll close this PR since I deleted a file. 
I'll create a new PR with the worksets sort-class change, and a new one with just one page updated!

**Pull request closed without merging**
