### PR TITLE
Uppmax quotas: display cpu quota decrease

### PR DESCRIPTION
**Pull request by kate-v-stepanova**

### CODE REVIEW

**Comment by ewels** [comment]
Looks good - is this on stage?

**Comment by kate-v-stepanova** [comment]
No, because we don't have this data on stage. But I can try to force taca to update tools-dev instead of tools

**Comment by kate-v-stepanova** [comment]
yes, now deployed on stage: https://genomics-status-stage.scilifelab.se/quotas

**Comment by ewels** [comment]
Nice 👍  Good to know that it doesn't break genstat even if there is no data ;)

**Pull request merged**
